# Generated by Django 4.2.11 on 2024-05-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cashcollector_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': ' Manager', 'verbose_name_plural': ' Managers'},
        ),
    ]
