# Generated by Django 4.2.11 on 2024-05-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': ' Customers'},
        ),
    ]
