# Generated by Django 4.2.11 on 2024-04-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0002_cashcollector_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollectorPocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collected_pocket', to='billing.customerbill')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pocket_values', to='users.cashcollector')),
            ],
        ),
        migrations.CreateModel(
            name='CentralSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('pocket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='accounting.cashcollectorpocket')),
            ],
        ),
    ]
