# Generated by Django 4.2.11 on 2024-05-01 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashcollectorpocket',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='centralsafe',
            name='amount',
        ),
        migrations.AlterField(
            model_name='cashcollectorpocket',
            name='collected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='centralsafe',
            name='transferred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
