# Generated by Django 4.2.11 on 2024-05-02 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_manager_options'),
        ('accounting', '0002_remove_cashcollectorpocket_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollectorTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_value', models.DecimalField(decimal_places=4, max_digits=40)),
                ('checkpoint_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_threshold_then', models.IntegerField()),
                ('days_threshold_then', models.IntegerField()),
                ('frozen', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='users.cashcollector')),
            ],
        ),
    ]
