# Generated by Django 4.2.11 on 2024-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_cashcollectortimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollectortimeline',
            name='transaction_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
            preserve_default=False,
        ),
    ]
